[book]
title = "Aragog"
authors =  [
    "Felix de Maneville: <felix.maneville@gmail.com>",
    "Qonfucius team <felix.maneville@qonfucius.team>"
]
description = "The aragog book covers all available features"
src = "book"
language = "en"
multilingual = false

[rust]
edition = "2018"

[build]
build-dir = "public"
create-missing = false

[preprocessor.graphviz]
command = "mdbook-graphviz"

[preprocessor.links]

[preprocessor.index]