[package]
name = "aragog"
version = "0.4.3"
authors = [
    "Felix de Maneville: <felix.maneville@gmail.com>",
    "Qonfucius team <felix.maneville@qonfucius.team>"
]
edition = "2018"
description = "A simple lightweight object-document mapper for ArangoDB"
keywords = ["ArangoDB", "Arango", "ORM", "ODM", "OGM"]
exclude =  ["examples", "tests", ".gitlab-ci.yml"]
categories = ["web-programming", "database"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/qonfucius/aragog"
documentation = "https://docs.rs/aragog"

[features]
default = [ ]
actix_http_error = ["actix-web"]
password_hashing = ["argonautica"]

[dependencies]
# ArangoDB driver
arangors = "^0.4"
# Used for string validation toolbox, not used otherwise
regex = "^1.3"
# Record trait has async methods
async-trait = "^0.1"
# Serialization and deserialization
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
# Log handling
log = "^0.4"
# Error definitions
thiserror = "^1.0"
# Numeric types
num = "^0.3"

actix-web = { version = "^3.0", optional = true }
argonautica = { version = "^0.2", optional = true }

[dev-dependencies]
tokio-test = "^0.2"
tokio = {version = "^0.2", features = ["rt-threaded", "macros"]}
# We add the "feature" option to avoid serde version conflict somehow
chrono = { version = "^0.4", features = ["serde"] }