[package]
name = "aragog"
version = "0.1.0"
authors = [
    "Felix de Maneville: <felix.maneville@gmail.com>",
    "Qonfucius team <felix.maneville@qonfucius.team>"
]
edition = "2018"
description = "A simple lightweight object-document mapper for ArangoDB"
keywords = ["ArangoDB", "Arango"]
categories = ["web-programming", "database"]
exclude =  ["examples", "tests"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://gitlab.com/qonfucius/aragog"
documentation = "https://docs.rs/aragog"

[dependencies]
# ArangoDB driver
arangors = "0.4.3"
# Used for string validation toolbox, not used otherwise
regex = "1.3.9"
# Record trait has async methods
async-trait = "0.1.36"
# Serialization and deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Log handling
log = "0.4.11"
# Error definitions
thiserror = "1.0.20"

[dev-dependencies]
tokio-test = "0.2.1"
tokio = {version = "0.2.22", features = ["rt-threaded", "macros"]}
# We add the "feature" option to avoid serde version conflict somehow
chrono = { version = "0.4.13", features = ["serde"] }