[package]
name = "aragog"
version = "0.6.1"
authors = [
    "Felix de Maneville: <felix.maneville@gmail.com>",
    "Qonfucius team <felix.maneville@qonfucius.team>"
]
edition = "2018"
description = "A simple lightweight object-document mapper for ArangoDB"
keywords = ["ArangoDB", "Arango", "ORM", "ODM", "OGM"]
exclude =  ["tests", ".gitlab-ci.yml"]
categories = ["web-programming", "database"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/qonfucius/aragog"
documentation = "https://docs.rs/aragog"

[features]
default = [ ]
actix = ["actix-web"]
open-api = ["paperclip"]
password_hashing = ["argonautica"]

[dependencies]
# ArangoDB driver
arangors = "0.4.4"
# Used for string validation toolbox, not used otherwise
regex = "1.4.2"
# Record trait has async methods
async-trait = "0.1.42"
# Serialization and deserialization
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
# Log handling
log = "0.4.11"
# Error definitions
thiserror = "1.0.22"
# Numeric types
num = "0.3.1"
# Self depedencies
aragog-macros = { path = "aragog_macros" }

actix-web = { version = "3.2.0", optional = true, default-features = false }
argonautica = { version = "0.2.0", optional = true }
paperclip = { git = "https://github.com/wafflespeanut/paperclip", branch = "master", optional = true, features = ["actix"] }

[dev-dependencies]
tokio-test = "0.2.1"
tokio = {version = "0.2.23", features = ["macros"]}
# We add the "feature" option to avoid serde version conflict somehow
chrono = { version = "0.4.19", features = ["serde"] }