[package]
name = "aragog_cli"
version = "0.3.3"
authors = [
    "Felix de Maneville: <felix.maneville@gmail.com>",
    "Qonfucius team <felix.maneville@qonfucius.team>"
]
edition = "2018"
license = "MIT"
description = "CLI for Aragog Crate"
exclude= ["example"]
categories = ["web-programming", "database"]
repository = "https://gitlab.com/qonfucius/aragog/-/tree/master/aragog_cli"
readme = "README.md"
homepage = "https://aragog.rs"

[[bin]]
name = "aragog"
path = "src/main.rs"
doc = false

[dependencies]
# Aragog
aragog = { path = "..", version = "0.14", features = ["blocking", "minimal_traits"], default-features = false }

arangors = { version = "0.5", features = ["blocking", "reqwest_blocking", "rocksdb"], default-features = false }
# TODO: remove this when arangors fixes https://github.com/fMeow/arangors/issues/79
typed-builder = "=0.9.0"
# Required until re-exported from arangors crate, latest version (0.2.3) is not compatible
uclient = { version = "0.1.3", features = ["blocking_reqwest"]}

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
# Describe output
prettytable-rs = "0.8"
# Log
log = "0.4"

# Time
chrono = "0.4"

# Command-line args
clap = { version = "=3.0.0-beta.2", features = ["yaml"] }

# error
thiserror = "1.0"